version: '3.8'
services:
  db:
    container_name: mongo-hackathon
    image: mongo:5.0.6
    environment:
      - MONGODB_USER=admin
      - MONGODB_PASS=pass
      - MONGODB_HOST=db
      - MONGODB_DATABASE=tokenTravel
    ports:
      - '27017:27017'
    volumes: 
      - ./data:/data/db
  
  mongo-express:
    container_name: mongo-express-interface
    image: mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-hackathon
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
    ports:
      - '8081:8081'
    volumes: 
      - ./data:/data/db
  app:
    build:
      context: .
      target: user
    image: king-of-dev-backend
    user: $USER_ID
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_NAME=yourdatabase
      - DB_HOST=mysql_db
      - DB_PORT=3306
      - DB_DIALECT=mysql
      - MONGO_URL=mongodb://admin:pass@db:27017/tokenTravel?authSource=admin
    command:
      - tail
      - -f
    volumes:
      - .:/app
volumes:
  db: {}
  npm-cache: